# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gt5OAOnYoTQJqkq3Lpgk6XiemE_yI-7F
"""

import streamlit as st
import pandas as pd
import joblib

# تحميل الموديل المحفوظ (catboost.pkl)
model = joblib.load("catboost.pkl")

st.title("🚀 Exoplanet Classification App")
st.write("أدخلي القيم التالية للتنبؤ إذا كان الكوكب مرشح (Candidate) أو لا:")

# تعريف المدخلات (هنا أخفّضنا عددها كمثال — ممكن نزودهم كلهم زي README)
koi_period = st.number_input("koi_period", value=1.0)
koi_duration = st.number_input("koi_duration", value=1.0)
koi_depth = st.number_input("koi_depth", value=1.0)
koi_prad = st.number_input("koi_prad", value=1.0)
koi_teq = st.number_input("koi_teq", value=500.0)
koi_insol = st.number_input("koi_insol", value=1.0)

# تحويل المدخلات إلى DataFrame بنفس شكل التدريب
X_new = pd.DataFrame([{
    "koi_period": koi_period,
    "koi_duration": koi_duration,
    "koi_depth": koi_depth,
    "koi_prad": koi_prad,
    "koi_teq": koi_teq,
    "koi_insol": koi_insol
}])

# عند الضغط على الزر → التنبؤ
if st.button("🔮 Predict"):
    prediction = model.predict(X_new)[0]
    probabilities = model.predict_proba(X_new)[0]

    st.write("### ✅ النتيجة:")
    if prediction == 1:
        st.success("هذا الكوكب **مرشح** (Candidate)")
    else:
        st.error("هذا الكوكب **ليس مرشح**")

    st.write("### 🔢 احتمالات النموذج:")
    st.json({
        "Not Candidate": f"{probabilities[0]:.2f}",
        "Candidate": f"{probabilities[1]:.2f}"
    })

